[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"

[build-dependencies]
cmake = "0.1.50"
gobuild = "0.1.0-alpha.1"
cc = "^1.0"
bindgen = "0.69.4"
anyhow = "*"
