# cargo-features = ['strip']

[cargo-new]
email = 'alex_cj96@foxmail.com'
name  = 'Cheng JIANG'
vcs   = 'git'

[profile.release]
codegen-units    = 1       # prefer efficiency to compile time
debug            = false   # no debug data
debug-assertions = false   # prune debug assertions
lto              = true    # link time optimization
opt-level        = 'z'     # optimize for size ("s" may also work)
panic            = 'abort' # use simple panics
strip            = true    # remove debug info
# incremental = false      # no incremental builds

[target.i686-pc-windows-gnu]
linker = 'i686-w64-mingw32-gcc'

[target.x86_64-pc-windows-gnu]
ar     = 'x86_64-w64-mingw32-gcc-ar'
linker = 'x86_64-w64-mingw32-gcc'

[target.x86_64-apple-darwin]
ar     = 'x86_64-apple-darwin14-ar'
linker = 'x86_64-apple-darwin14-clang'

[target.mips-unknown-linux-musl]
ar     = 'mips-openwrt-linux-musl-ar'
linker = 'mips-openwrt-linux-musl-gcc'

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "link-arg=-zstack-size=8192", # shrink the heap
]

[term]
verbose = false

[build]
jobs      = 4
rustflags = ["-C", "target-cpu=native"]

[net]
git-fetch-with-cli = false

[profile.profiling]
debug    = true
inherits = "release"

# [target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
#
# [source.crates-io]
# registry = "https://github.com/rust-lang/crates.io-index"
# replace-with = 'ustc'
# [source.ustc]
# registry = "git://mirrors.ustc.edu.cn/crates.io-index"

# [registries.crates-io]
# protocol = "sparse"
#
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
