[book]
authors      = ["CJ"]
language     = "en"
multilingual = false
src          = "src"
title        = "Untitled"


[preprocessor.katex]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.plantuml]
plantuml-cmd = "plantuml"

# [preprocessor.toc]
# command  = "mdbook-toc"
# renderer = ["html"]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
[output.html.print]
enable = true

# [output.pdf]
