[foxmail]
server = "imap.qq.com"
port = 993
username = "alex_cj96@foxmail.com"
# sudo apt install libsecret-tools
# secret-tool store --label='Password for alex_cj96@foxmail.com' email foxmail
pwcmd = "secret-tool lookup email foxmail"
